class CatalogData {
  CatalogData(
      this.name,
      this.vendorName,
      this.imagePath,
      this.calories,
      this.grams,
      this.rating,
      this.price,
      this.isFavorite,
      this.isInStock,
      this.description);

  String name, vendorName, imagePath, description;
  double calories, grams, rating, price;
  bool isFavorite, isInStock;
}

List<CatalogData> myDummyCatalogData = [
  CatalogData(
      'Beef',
      'Sanfri Meats',
      'assets/images/meatCategories/Beef.png',
      250,
      100,
      4.7,
      33.2,
      true,
      true,
      'Beef has 250 calories per gram. This meat promotes weight loss by converting fat into energy. Beef has many nutrients and non-essential amino acids, it strengthens immunity and longevity.'),
  CatalogData(
      'Camel',
      'Maliume Meats',
      'assets/images/meatCategories/Camel.png',
      136,
      100,
      4.3,
      43.4,
      false,
      true,
      'Camel meat is a good source of protein. It is much healthier because it contains less fat and has lower levels of cholesterol in the fat than other meats. It is also relatively high in polyunsaturated fatty acids in comparison to beef and other meats. It is also characterized by low levels of cholesterol as compared to other meats, making it a healthy food for humans.'),
  CatalogData(
      'Chicken',
      'Standery Meats',
      'assets/images/meatCategories/Chicken.png',
      239,
      100,
      3.3,
      54.2,
      false,
      true,
      'Chicken meat has 239 calories per 100 grams. Chicken is one of the most consumed, popular, and liked types of meat. Not only is chicken tasty but it has numerous health benefits.'),
  CatalogData(
      'Crab',
      'Cordova Meats shop',
      'assets/images/meatCategories/Crab.png',
      97,
      100,
      4.4,
      23.7,
      true,
      true,
      'Crabmeat has the lowest calories per 100g. Crab is abundant in protein and iron. Eating crab produces red blood cells in the body which prevents anemia.'),
  CatalogData(
      'Duck',
      'Aseel Meats sale',
      'assets/images/meatCategories/Duck.png',
      337,
      100,
      4.8,
      33.9,
      true,
      false,
      'Duck contains 337 calories per 100 grams. Duck meat has essential amino acids which are responsible for producing energy.'),
  CatalogData(
      'Goat',
      'Shiekh Meats',
      'assets/images/meatCategories/Goat.png',
      143,
      100,
      3.9,
      59.1,
      true,
      true,
      'Goat meat is the best replacement for other red meats. It is low in fat and cholesterol which means it does not add any unwanted calories. Also, it has a profuse amount of calcium and potassium in it.'),
  CatalogData(
      'Lamb',
      'Bolium Meats sale',
      'assets/images/meatCategories/Lamp.png',
      267,
      100,
      3.5,
      56.5,
      true,
      true,
      'Lamb meat is a treasure box of vitamin B1, B2 and vitamin E. These vitamins support metabolism, skin condition, blood pressure, aging, and healing. That’s why doctors suggest eating lamb’s meat after surgeries.'),
  CatalogData(
      'Lobster',
      'Sea Sale Meats',
      'assets/images/meatCategories/Lobster.png',
      128,
      100,
      4.1,
      13.2,
      false,
      true,
      'Lobster is a shellfish, full of nutrients such as copper, selenium, zinc, phosphorus, vitamin B12, magnesium, vitamin E including omega-3 fatty acids. It stabilizes hormones in the body.'),
  CatalogData(
      'Rabbit',
      'Libnan Meats',
      'assets/images/meatCategories/Rabbit.png',
      173,
      100,
      4.7,
      36.3,
      false,
      true,
      'It is unlike other meats and has many health benefits. It has a good bearable smell and does not have a strong flavor.'),
  CatalogData(
      'Salmon',
      'Safari Meats',
      'assets/images/meatCategories/Salmon.png',
      206,
      100,
      4.6,
      43.7,
      true,
      true,
      'calories per 100 grams. Salmon meat is very popular for its flavor and health benefits. It provides us nutrients our body can not produce like Omega 3 fatty acids.'),
  CatalogData(
      'Shrimp',
      'aladin Meats',
      'assets/images/meatCategories/Shrimp.png',
      99,
      100,
      3.7,
      53.9,
      false,
      true,
      'Shrimps are low in calories and high in cholesterol. Many people eat shrimp on a diet Because they are low in carbohydrates. Shrimp meat has Phosphorus, Copper, Zinc, Magnesium, Calcium, Potassium, Iron, Manganese. The biggest concern with shrimps is the high amount of cholesterol. Some people can also have allergies to shrimps.'),
  CatalogData(
      'Tuna',
      'Ghulam Meats shop',
      'assets/images/meatCategories/Tuna.png',
      132,
      100,
      4.4,
      37.3,
      true,
      true,
      'Tuna is a fish found in salty water which is extremely beneficial for health. Tuna meat has selenium that has antioxidant properties which keep the immune system healthy.'),
];
